version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    labels:
      - "angular"
      - "dependencies"
    reviewers:
      - "zaidi-01"
      - "StevieShibly8"
      - "NilinReza"
      - "JJTomines"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      angular:
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - ".net"
      - "dependencies"
    reviewers:
      - "zaidi-01"
      - "StevieShibly8"
      - "NilinReza"
      - "JJTomines"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      microsoft:
        patterns:
          - "Microsoft*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
